# Default config for Vagrant
# use vagrantconfig_local.yml to override these settings and put it to .gitignore

# conf gets passed to puppet scripts
conf:
  ruby_version: "2.0.0-p247"
  databases:
    - "postgres"
  # or
    # - "mysql"
  # or
    # - "sqlite3"

  packages:
    - "vim"
    - "git"
    # - "imagemagick"
    # - ...

# All these are used inside Vagrantfile
name: "project_name"

box_name: "precise64"
box_url: "http://files.vagrantup.com/precise64.box"

memory: 512 # megabytes for VM
guest_ip: "192.168.2.60"

ports:
  - {guest: 3000, host: 3000} # rails default
  - {guest: 4567, host: 4567} # sinatra
  - {guest: 1234, host: 1234} # middleman

timezone: "Europe/Ljubljana"
