# Default config for Vagrant

# Don't change this; use vagrantconfig_local.yml to override these
# settings instead.

name: "booby_trap"
database: "postgres"
#database: "mysql"

box_name: "precise64"
box_url: "http://files.vagrantup.com/precise64.box"
ruby: "mri"

memory: 512 # megabytes for VM
guest_ip: "192.168.2.60"

host_development_dir: "~/development"
guest_development_dir: "~/development"

ports:
  - {guest: 3000, host: 3000}

timezone: "Europe/Ljubljana"

mysql_user: "postgres"
mysql_password: "postgres"
