# Default config for Vagrant

# Don't change this; use vagrantconfig_local.yml to override these
# settings instead.

name: "booby_trap"

ruby: "mri"
ruby_version: "2.0.0-p0"
database: "postgres" # or "mysql"

box_name: "precise64"
box_url: "http://files.vagrantup.com/precise64.box"

memory: 512 # megabytes for VM
guest_ip: "192.168.2.60"

host_development_dir: "~/development"
guest_development_dir: "~/development"

ports:
  - {guest: 3000, host: 3000}

timezone: "Europe/Ljubljana"
